name: tesscam
base: core18
version: '0.1'
summary: Process TeslaCam videos to nicer format
description: |
  This will process TeslaCam fotage to a nicer format. I will merge
  the files togeter to a single long video.

grade: stable
confinement: strict

apps:
  list:
    command: bin/list.sh
    adapter: full
    plugs:
      - removable-media

  detect:
    command: bin/detect.sh
    adapter: full
    plugs:
      - removable-media

  encode:
    command: bin/encode.sh
    adapter: full
    plugs:
      - removable-media
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"


parts:
  tesscam:
    plugin: dump
    source: src
    stage-packages:
      - ffmpeg
      - libpulse0
      - libslang2